stages:
  - test
  - build_doc

default:
  image: "gitlab.version.fz-juelich.de:5555/rittich2/allium/allium-full"
  tags:
    - public-docker
  before_script:
    - pwd
    - ln -s $PWD /home/developer/source

test_suite_minimal:
  stage: test
  except:
    - pages
  image: "gitlab.version.fz-juelich.de:5555/rittich2/allium/allium-minimal"
  script:
    - container-init.sh tests

test_suite_full:
  stage: test
  except:
    - pages
  script:
    - container-init.sh tests

pages:
  stage: build_doc
  only:
    - master
    - pages
  script:
    - cmake .
    - make api-docs
    - mkdir public
    - ls public
    - cp -vr doc/api/html -T public
  artifacts:
    paths:
      - public
