stages:
  - build_and_test
  - deploy

default:
  image: "gitlab.version.fz-juelich.de:5555/rittich2/allium/allium-full"
  tags:
    - public-docker
  before_script:
    - pwd
    - ln -s $PWD /home/developer/source

test_suite_minimal:
  stage: build_and_test
  except:
    - pages
  image: "gitlab.version.fz-juelich.de:5555/rittich2/allium/allium-minimal"
  script:
    - container-init.sh tests

test_suite_full:
  stage: build_and_test
  except:
    - pages
  script:
    - container-init.sh tests

test_suite_release:
  stage: build_and_test
  except:
    - pages
  script:
    - container-init.sh tests release

api_docs:
  stage: build_and_test
  script:
    - cmake .
    - make api-docs
    - mkdir public
    - ls public
    - cp -vr doc/html -T public
  artifacts:
    paths:
      - doc/html
    expire_in: 15 days

pages:
  stage: deploy
  only:
    - master
    - pages
  script:
    - cp -vr doc/html -T public
  artifacts:
    paths:
      - public
