stages:
  - tests

default:
  image: "gitlab.version.fz-juelich.de:5555/rittich2/allium/allium-full"
  tags:
    - public-docker
  before_script:
    - pwd
    - ln -s $PWD /home/developer/source

test_suite_minimal:
  stage: tests
  image: "gitlab.version.fz-juelich.de:5555/rittich2/allium/allium-minimal"
  script:
    - container-init.sh tests

test_suite_full:
  stage: tests
  script:
    - container-init.sh tests
