name: GitHub Pages

on:
  push:
    branches:
      - improve-doc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -qy openmpi-bin
      - run: ls
      - run: echo ${{ github.workspace }}
      - run: ./scripts/publish-gh-pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
